#ifndef COMMANDLINE_VIDEOSTORE_CPP_MOVIE_UTILITIES_H
#define COMMANDLINE_VIDEOSTORE_CPP_MOVIE_UTILITIES_H

#include <string>

std::string getMovieFileLocation();

#endif //COMMANDLINE_VIDEOSTORE_CPP_MOVIE_UTILITIES_H
